package label_injector

import (
	"io/ioutil"
	"shopstic/prom-labels-injector/config"
	"strings"
	"testing"
)

func TestInjectLabels(t *testing.T) {
	input := ReadFile("test-metrics-input.txt", t)
	expected := ReadFile("test-metrics-expected.txt", t)
	settings := config.LabelInjectorConfig{
		Labels: []config.LabelConfig{
			config.LabelConfig{
				Label: "az",
				Value: "us-east-1a",
			},
			config.LabelConfig{
				Label: "instance",
				Value: "c6g.12xlarge",
			},
		},
	}
	result := strings.TrimSpace(InjectLabels(input, &settings))
	if result != expected {
		t.Fatal("Expected metrics are different than the one generated by InjectLabels")
	}
}

func ReadFile(name string, t *testing.T) string {
	content, err := ioutil.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	return strings.TrimSpace(string(content))
}
