name: CI Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-app:
    name: Build app image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Github ref name
        id: ref_name
        run: |
          BRANCH=""
          TAG=""
          if [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]; then
            BRANCH=${GITHUB_REF#refs/heads/}
          fi

          if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ "${BRANCH}" == "main" ]]; then
            TAG=${GITHUB_SHA}
          fi

          echo "::set-output name=branch::${BRANCH}"
          echo "::set-output name=tag::${TAG}"

      - name: Build and push app Docker image latest
        uses: shopstic/buildkit-action@1.0.12
        if: steps.ref_name.outputs.branch == 'main'
        with:
          context: ${{ github.workspace }}
          image: shopstic/prom-labels-injector
          tag: ${{ github.sha }}
          additionalTags: latest
          skipIfExists: false

      - name: Build and push app Docker image to tag
        uses: shopstic/buildkit-action@1.0.12
        if: steps.ref_name.outputs.tag != ''
        with:
          context: ${{ github.workspace }}
          image: shopstic/prom-labels-injector
          tag: ${{ steps.ref_name.outputs.tag }}
          skipIfExists: false
