name: Dev

on: [push]

defaults:
  run:
    shell: bash

env:
  IMAGE_REPOSITORY: public.ecr.aws/shopstic
  IMAGE_NAME: prom-labels-injector

jobs:
  build:
    name: Build image
    runs-on:
      - self-hosted
      - nix
      - general
      - ${{ matrix.arch.image }}-linux
      - small
    strategy:
      matrix:
        arch:
          - nix: x86_64
            image: amd64
          - nix: aarch64
            image: arm64
    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Build container images
        run: |-
          nix build -L -v '.#packages.${{ matrix.arch.nix }}-linux.image'

      - name: Push
        env:
          GITHUB_SHA: ${{ github.sha }}
          IMAGE_ARCH: ${{ matrix.arch.image }}
        shell: nix develop -v -c bash {0}
        run: |-
          IMAGE_TAG="dev-${IMAGE_ARCH}-${GITHUB_SHA}"

          skopeo --insecure-policy copy \
            docker-archive:./result \
            docker://"${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":"${IMAGE_TAG}"

  push-multi-arch:
    name: Push multi-arch image manifest
    runs-on:
      - self-hosted
      - nix
      - general
      - arm64-linux
      - small
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Push multi-arch manifest
        shell: nix develop -v -c bash {0}
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |-
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/"${IMAGE_NAME}":dev-"${GITHUB_SHA}"
